### ISSUE TITLE
Example expression from README not producing expected results

### ISSUE THREAD

**Issue by cdupuis** [atomist-skills/string-replace-skill#39]
I think I followed the example from the README and entered `s/([a-zA-Z]*?)_([a-zA-Z])/$1\U$2/g` as the pattern. 

This produced the following PR https://github.com/atomist-playground/org-sdm/pull/2/files.

**Comment by slimslenderslacks** [comment]
This expression actually should be:

```
s/([a-zA-Z]*?)_([a-zA-Z])/$1\u$2/g
```

with a lower-case \u.  Both work because that second capture group only captures one character but I think \u is more natural since \u only uppercases the next character where as \U goes into uppercase everything mode.

I've migrated support for these gnu extensions our substitution command.
